export const gamesData = [
  {
    Name: "Nobunaga no Yabou DS",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Strategy",
    Publisher: "Tecmo Koei",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.01",
    Other_Sales: "0",
    Global_Sales: "0.01",
  },
  {
    Name: "God Eater Off Shot: Soma Shikkuzaru-hen Twin Pack & Animation Vol.4",
    Platform: "PS4",
    Year_of_Release: "2016",
    Genre: "Action",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Cesar Millan's Dog Whisperer",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Ubisoft",
    NA_Sales: "0.04",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.05",
    User_Score: "8.6",
    User_Count: "9",
    Developer: "Ubisoft",
  },
  {
    Name: "Doctor Who: Return to Earth",
    Platform: "Wii",
    Year_of_Release: "2010",
    Genre: "Adventure",
    Publisher: "Asylum Entertainment",
    NA_Sales: "0",
    EU_Sales: "0.16",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.18",
  },
  {
    Name: "Pro Evolution Soccer 2013",
    Platform: "PS3",
    Year_of_Release: "2012",
    Genre: "Sports",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0.18",
    EU_Sales: "0.63",
    JP_Sales: "0.49",
    Other_Sales: "0.24",
    Global_Sales: "1.53",
    Critic_Score: "82",
    Critic_Count: "37",
    User_Score: "6.7",
    User_Count: "146",
    Developer: "Konami",
  },
  {
    Name: "Hunter x Hunter: Wonder Adventure",
    Platform: "PSP",
    Year_of_Release: "2012",
    Genre: "Action",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.04",
    Other_Sales: "0",
    Global_Sales: "0.04",
  },
  {
    Name: "Dokapon Journey",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Role-Playing",
    Publisher: "Sting",
    NA_Sales: "0.05",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.05",
    Critic_Score: "60",
    Critic_Count: "16",
    User_Score: "7",
    User_Count: "8",
    Developer: "Suzak",
  },
  {
    Name: "From Russia With Love",
    Platform: "PSP",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "Electronic Arts",
    NA_Sales: "0.07",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.08",
    Critic_Score: "61",
    Critic_Count: "33",
    User_Score: "6.9",
    User_Count: "12",
    Developer: "Rebellion",
  },
  {
    Name: "Super Mario Bros. 3",
    Platform: "GBA",
    Year_of_Release: "2003",
    Genre: "Platform",
    Publisher: "Nintendo",
    NA_Sales: "2.93",
    EU_Sales: "1.25",
    JP_Sales: "0.83",
    Other_Sales: "0.2",
    Global_Sales: "5.2",
  },
  {
    Name: "Robotron 64",
    Platform: "N64",
    Year_of_Release: "1998",
    Genre: "Shooter",
    Publisher: "GT Interactive",
    NA_Sales: "0.07",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.09",
  },
  {
    Name: "Nintendogs",
    Platform: "DS",
    Year_of_Release: "2005",
    Genre: "Simulation",
    Publisher: "Nintendo",
    NA_Sales: "9.05",
    EU_Sales: "10.95",
    JP_Sales: "1.93",
    Other_Sales: "2.74",
    Global_Sales: "24.67",
  },
  {
    Name: "PhotoKano",
    Platform: "PSP",
    Year_of_Release: "2012",
    Genre: "Adventure",
    Publisher: "Kadokawa Shoten",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.09",
    Other_Sales: "0",
    Global_Sales: "0.09",
  },
  {
    Name: "Medal of Honor: Rising Sun",
    Platform: "PS2",
    Year_of_Release: "2003",
    Genre: "Shooter",
    Publisher: "Electronic Arts",
    NA_Sales: "1.98",
    EU_Sales: "2.23",
    JP_Sales: "0.13",
    Other_Sales: "0.8",
    Global_Sales: "5.13",
    Critic_Score: "68",
    Critic_Count: "30",
    User_Score: "7.6",
    User_Count: "100",
    Developer: "EA LA",
  },
  {
    Name: "Pokemon Mystery Dungeon: Gates to Infinity",
    Platform: "3DS",
    Year_of_Release: "2012",
    Genre: "Role-Playing",
    Publisher: "Nintendo",
    NA_Sales: "0.44",
    EU_Sales: "0.29",
    JP_Sales: "0.47",
    Other_Sales: "0.07",
    Global_Sales: "1.27",
    Critic_Score: "59",
    Critic_Count: "46",
    User_Score: "6.3",
    User_Count: "134",
    Developer: '"Nintendo',
  },
  {
    Name: "Shark Tale",
    Platform: "PS2",
    Year_of_Release: "2004",
    Genre: "Action",
    Publisher: "Activision",
    NA_Sales: "0.37",
    EU_Sales: "0.29",
    JP_Sales: "0",
    Other_Sales: "0.1",
    Global_Sales: "0.75",
    Critic_Score: "69",
    Critic_Count: "30",
    User_Score: "6.5",
    User_Count: "6",
    Developer: "Edge of Reality",
  },
  {
    Name: "Cabela's Dangerous Hunts 2011",
    Platform: "X360",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "0.28",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.32",
    Critic_Score: "55",
    Critic_Count: "7",
    Developer: "Activision",
  },
  {
    Name: "Putty Squad",
    Platform: "PSV",
    Year_of_Release: "2013",
    Genre: "Platform",
    Publisher: "System 3",
    NA_Sales: "0.01",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.03",
    User_Score: "8.2",
    User_Count: "6",
    Developer: "System 3",
  },
  {
    Name: "Bleach: Heat the Soul 6",
    Platform: "PSP",
    Year_of_Release: "2009",
    Genre: "Fighting",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.09",
    Other_Sales: "0",
    Global_Sales: "0.09",
  },
  {
    Name: "Dragon Ball: Raging Blast",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Fighting",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.36",
    EU_Sales: "0.08",
    JP_Sales: "0.02",
    Other_Sales: "0.04",
    Global_Sales: "0.51",
    Critic_Score: "56",
    Critic_Count: "29",
    User_Score: "7.5",
    User_Count: "33",
    Developer: "Spike",
  },
  {
    Name: "Pitfall!",
    Platform: "2600",
    Year_of_Release: "1981",
    Genre: "Platform",
    Publisher: "Activision",
    NA_Sales: "4.21",
    EU_Sales: "0.24",
    JP_Sales: "0",
    Other_Sales: "0.05",
    Global_Sales: "4.5",
  },
  {
    Name: "The Godfather: Dons Edition",
    Platform: "PS3",
    Year_of_Release: "2007",
    Genre: "Action",
    Publisher: "Electronic Arts",
    NA_Sales: "0.25",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.29",
  },
  {
    Name: "World Snooker Championship 2007",
    Platform: "PS3",
    Year_of_Release: "2007",
    Genre: "Sports",
    Publisher: "Sega",
    NA_Sales: "0",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.1",
  },
  {
    Name: "The Croods: Prehistoric Party!",
    Platform: "DS",
    Year_of_Release: "2013",
    Genre: "Misc",
    Publisher: "D3Publisher",
    NA_Sales: "0.03",
    EU_Sales: "0.04",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.07",
  },
  {
    Name: "NBA Live 06",
    Platform: "GC",
    Year_of_Release: "2005",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.25",
    EU_Sales: "0.07",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.33",
    Critic_Score: "76",
    Critic_Count: "14",
    Developer: "EA Canada",
  },
  {
    Name: "Touch Detective (JP sales)",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "505 Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Memories Off: Sorekara Again",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "KID",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Lionel Trains: On Track",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "DSI Games",
    NA_Sales: "0.04",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.04",
    Critic_Score: "47",
    Critic_Count: "4",
    Developer: "Black Lantern Studios",
  },
  {
    Name: "Godzilla Unleashed: Double Smash",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Action",
    Publisher: "Atari",
    NA_Sales: "0.11",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.12",
    Critic_Score: "28",
    Critic_Count: "18",
    User_Score: "4.9",
    User_Count: "8",
    Developer: "Santa Cruz Games",
  },
  {
    Name: "Agatha Christie: Evil Under the Sun",
    Platform: "Wii",
    Year_of_Release: "2008",
    Genre: "Adventure",
    Publisher: "The Adventure Company",
    NA_Sales: "0.06",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.08",
    Critic_Score: "46",
    Critic_Count: "6",
    User_Score: "7.3",
    User_Count: "6",
    Developer: "AWE Games",
  },
  {
    Name: "Rogue Trip: Vacation 2012",
    Platform: "PS",
    Year_of_Release: "1998",
    Genre: "Racing",
    Publisher: "GT Interactive",
    NA_Sales: "0.21",
    EU_Sales: "0.14",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.38",
  },
  {
    Name: "Parfait",
    Platform: "PSV",
    Year_of_Release: "2015",
    Genre: "Adventure",
    Publisher: "TGL",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.03",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "Fairy Tail: Zelef Kakusei",
    Platform: "PSP",
    Year_of_Release: "2012",
    Genre: "Action",
    Publisher: "Unknown",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.07",
    Other_Sales: "0",
    Global_Sales: "0.07",
  },
  {
    Name: "3D Baseball",
    Platform: "PS",
    Year_of_Release: "1996",
    Genre: "Sports",
    Publisher: "BMG Interactive Entertainment",
    NA_Sales: "0.02",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "The Guided Fate Paradox",
    Platform: "PS3",
    Year_of_Release: "2013",
    Genre: "Role-Playing",
    Publisher: "Nippon Ichi Software",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.06",
    Other_Sales: "0",
    Global_Sales: "0.07",
    Critic_Score: "74",
    Critic_Count: "27",
    User_Score: "7.8",
    User_Count: "66",
    Developer: "Nippon Ichi Software",
  },
  {
    Name: "Midway Arcade Treasures",
    Platform: "PS2",
    Year_of_Release: "2003",
    Genre: "Misc",
    Publisher: "Midway Games",
    NA_Sales: "0.72",
    EU_Sales: "0.56",
    JP_Sales: "0",
    Other_Sales: "0.19",
    Global_Sales: "1.46",
    Critic_Score: "76",
    Critic_Count: "22",
    Developer: "Midway",
  },
  {
    Name: "NHL 06",
    Platform: "XB",
    Year_of_Release: "2005",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.19",
    EU_Sales: "0.05",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.25",
    Critic_Score: "79",
    Critic_Count: "35",
    User_Score: "8.4",
    User_Count: "18",
    Developer: "EA Canada",
  },
  {
    Name: "Monster High: Ghoul Spirit",
    Platform: "Wii",
    Year_of_Release: "2011",
    Genre: "Misc",
    Publisher: "THQ",
    NA_Sales: "0.42",
    EU_Sales: "0.07",
    JP_Sales: "0",
    Other_Sales: "0.04",
    Global_Sales: "0.53",
    Developer: "THQ",
  },
  {
    Name: "Monster Hunter Frontier Online: Forward 2",
    Platform: "X360",
    Year_of_Release: "2011",
    Genre: "Role-Playing",
    Publisher: "Capcom",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.03",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "Stunt GP",
    Platform: "PS2",
    Year_of_Release: "2001",
    Genre: "Racing",
    Publisher: "Titus",
    NA_Sales: "0.02",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.05",
    Critic_Score: "49",
    Critic_Count: "8",
    User_Score: "8.1",
    User_Count: "9",
    Developer: "Team 17",
  },
  {
    Name: "American Girl: Julie Finds a Way",
    Platform: "DS",
    Year_of_Release: "2007",
    Genre: "Adventure",
    Publisher: "THQ",
    NA_Sales: "0.1",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.1",
    Developer: "Webfoot Technologies",
  },
  {
    Name: "Hakuouki: Reimeiroku",
    Platform: "PS2",
    Year_of_Release: "2010",
    Genre: "Adventure",
    Publisher: "Idea Factory",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.05",
    Other_Sales: "0",
    Global_Sales: "0.05",
  },
  {
    Name: "The Book of Unwritten Tales",
    Platform: "PC",
    Year_of_Release: "2009",
    Genre: "Adventure",
    Publisher: "HMH Interactive",
    NA_Sales: "0",
    EU_Sales: "0.08",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.1",
    Critic_Score: "82",
    Critic_Count: "32",
    User_Score: "8.2",
    User_Count: "144",
    Developer: "KING Art",
  },
  {
    Name: "Madagascar",
    Platform: "PS2",
    Year_of_Release: "2005",
    Genre: "Platform",
    Publisher: "Activision",
    NA_Sales: "0.78",
    EU_Sales: "0.45",
    JP_Sales: "0",
    Other_Sales: "0.07",
    Global_Sales: "1.31",
    Critic_Score: "69",
    Critic_Count: "25",
    User_Score: "7.4",
    User_Count: "25",
    Developer: "Toys for Bob",
  },
  {
    Name: "Metal Slug Anthology",
    Platform: "PSP",
    Year_of_Release: "2007",
    Genre: "Shooter",
    Publisher: "Ignition Entertainment",
    NA_Sales: "0.02",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0.01",
    Global_Sales: "0.05",
    Critic_Score: "78",
    Critic_Count: "26",
    User_Score: "7.4",
    User_Count: "25",
    Developer: "Terminal Reality",
  },
  {
    Name: "The Price is Right",
    Platform: "DS",
    Year_of_Release: "2008",
    Genre: "Misc",
    Publisher: "Ubisoft",
    NA_Sales: "0.46",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.04",
    Global_Sales: "0.49",
    Developer: "Ludia Inc.",
  },
  {
    Name: "Disney's Brother Bear",
    Platform: "GBA",
    Year_of_Release: "2003",
    Genre: "Action",
    Publisher: "THQ",
    NA_Sales: "0.28",
    EU_Sales: "0.1",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.39",
    Developer: "Vicarious Visions",
  },
  {
    Name: "Re-Volt",
    Platform: "N64",
    Year_of_Release: "1999",
    Genre: "Racing",
    Publisher: "Acclaim Entertainment",
    NA_Sales: "0.14",
    EU_Sales: "0.04",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.18",
  },
  {
    Name: "Teenage Mutant Ninja Turtles 3: Mutant Nightmare",
    Platform: "DS",
    Year_of_Release: "2005",
    Genre: "Action",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0.05",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.06",
    Critic_Score: "58",
    Critic_Count: "10",
    User_Score: "7",
    User_Count: "5",
    Developer: "Konami",
  },
  {
    Name: "Kabushiki Baibai Trainer: Kabutore!",
    Platform: "DS",
    Year_of_Release: "2006",
    Genre: "Simulation",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.1",
    Other_Sales: "0",
    Global_Sales: "0.1",
  },
  {
    Name: "Zoo Tycoon: Complete Collection",
    Platform: "PC",
    Year_of_Release: "2003",
    Genre: "Strategy",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "0.03",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.06",
    User_Score: "8",
    User_Count: "8",
    Developer: "Blue Fang Games",
  },
  {
    Name: "PokePark 2: Wonders Beyond",
    Platform: "Wii",
    Year_of_Release: "2011",
    Genre: "Action",
    Publisher: "Nintendo",
    NA_Sales: "0.26",
    EU_Sales: "0.19",
    JP_Sales: "0.27",
    Other_Sales: "0.04",
    Global_Sales: "0.75",
    Critic_Score: "60",
    Critic_Count: "18",
    User_Score: "7",
    User_Count: "27",
    Developer: "Creatures Inc.",
  },
  {
    Name: "Curious George",
    Platform: "XB",
    Year_of_Release: "2006",
    Genre: "Action",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0.02",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
    Critic_Score: "57",
    Critic_Count: "11",
    Developer: "Monkey Bar Games",
  },
  {
    Name: "Glover",
    Platform: "N64",
    Year_of_Release: "1998",
    Genre: "Platform",
    Publisher: "Hasbro Interactive",
    NA_Sales: "0.72",
    EU_Sales: "0.17",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.91",
  },
  {
    Name: "Ys: The Oath in Felghana",
    Platform: "PSP",
    Year_of_Release: "2010",
    Genre: "Role-Playing",
    Publisher: "Falcom Corporation",
    NA_Sales: "0.09",
    EU_Sales: "0",
    JP_Sales: "0.04",
    Other_Sales: "0.01",
    Global_Sales: "0.15",
    Critic_Score: "80",
    Critic_Count: "25",
    User_Score: "8.3",
    User_Count: "57",
    Developer: "Falcom",
  },
  {
    Name: "Pokemon Gold/Pokemon Silver",
    Platform: "GB",
    Year_of_Release: "1999",
    Genre: "Role-Playing",
    Publisher: "Nintendo",
    NA_Sales: "9",
    EU_Sales: "6.18",
    JP_Sales: "7.2",
    Other_Sales: "0.71",
    Global_Sales: "23.1",
  },
  {
    Name: "The Sims 2: Castaway",
    Platform: "Wii",
    Year_of_Release: "2007",
    Genre: "Simulation",
    Publisher: "Electronic Arts",
    NA_Sales: "0.44",
    EU_Sales: "0.63",
    JP_Sales: "0",
    Other_Sales: "0.14",
    Global_Sales: "1.2",
    Critic_Score: "73",
    Critic_Count: "19",
    User_Score: "8.2",
    User_Count: "10",
    Developer: "Maxis",
  },
  {
    Name: "Iron Man / X-O Manowar in Heavy Metal",
    Platform: "PS",
    Year_of_Release: "1996",
    Genre: "Platform",
    Publisher: "Acclaim Entertainment",
    NA_Sales: "0.05",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.08",
  },
  {
    Name: "NHL 09",
    Platform: "PS2",
    Year_of_Release: "2008",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.07",
    EU_Sales: "0.06",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.15",
    User_Score: "7.6",
    User_Count: "7",
    Developer: "EA Canada",
  },
  {
    Name: "Tiger Woods PGA Tour 10",
    Platform: "PS2",
    Year_of_Release: "2009",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "0.12",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0.13",
    Global_Sales: "0.26",
    Developer: "EA Tiburon",
  },
  {
    Name: "Little League World Series Baseball 2010",
    Platform: "X360",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "0.09",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.1",
    Critic_Score: "55",
    Critic_Count: "4",
    Developer: "Now Production",
  },
  {
    Name: "Dungeon Hunter Alliance",
    Platform: "PSV",
    Year_of_Release: "2012",
    Genre: "Action",
    Publisher: "Ubisoft",
    NA_Sales: "0.07",
    EU_Sales: "0.09",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.2",
    Critic_Score: "49",
    Critic_Count: "34",
    User_Score: "6.4",
    User_Count: "61",
    Developer: "Ubisoft",
  },
  {
    Name: "I Heart Geeks",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Puzzle",
    Publisher: "CDV Software Entertainment",
    NA_Sales: "0.02",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "The Smurfs 2",
    Platform: "DS",
    Year_of_Release: "2013",
    Genre: "Platform",
    Publisher: "Ubisoft",
    NA_Sales: "0",
    EU_Sales: "0.17",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.18",
    Developer: "WayForward",
  },
  {
    Name: "Jak X: Combat Racing",
    Platform: "PS2",
    Year_of_Release: "2005",
    Genre: "Racing",
    Publisher: "Sony Computer Entertainment",
    NA_Sales: "0.45",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0.07",
    Global_Sales: "0.55",
    Critic_Score: "76",
    Critic_Count: "46",
    User_Score: "7.7",
    User_Count: "63",
    Developer: "Naughty Dog",
  },
  {
    Name: "Mahou Sensei Negima! Kagai Jugyou ~Otome no Dokidoki Beachside~",
    Platform: "PS2",
    Year_of_Release: "2006",
    Genre: "Adventure",
    Publisher: "Konami Digital Entertainment",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.03",
    Other_Sales: "0",
    Global_Sales: "0.03",
  },
  {
    Name: "Pariah",
    Platform: "XB",
    Year_of_Release: "2005",
    Genre: "Action",
    Publisher: "Hip Interactive",
    NA_Sales: "0.08",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.1",
    Critic_Score: "70",
    Critic_Count: "52",
    User_Score: "7.4",
    User_Count: "19",
    Developer: "Digital Extremes",
  },
  {
    Name: "Metroid Prime Pinball",
    Platform: "DS",
    Year_of_Release: "2005",
    Genre: "Misc",
    Publisher: "Nintendo",
    NA_Sales: "0.21",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0.02",
    Global_Sales: "0.25",
    Critic_Score: "79",
    Critic_Count: "51",
    User_Score: "7.9",
    User_Count: "32",
    Developer: "Fuse Games Limited",
  },
  {
    Name: "NASCAR The Game: Inside Line",
    Platform: "X360",
    Year_of_Release: "2012",
    Genre: "Racing",
    Publisher: "Activision",
    NA_Sales: "0.09",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.1",
    Critic_Score: "72",
    Critic_Count: "7",
    User_Score: "3.4",
    User_Count: "27",
    Developer: "Eutechnyx",
  },
  {
    Name: "Tomb Raider: The Prophecy",
    Platform: "GBA",
    Year_of_Release: "2002",
    Genre: "Action",
    Publisher: "Ubisoft",
    NA_Sales: "0.1",
    EU_Sales: "0.04",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.14",
    Critic_Score: "66",
    Critic_Count: "20",
    User_Score: "8.8",
    User_Count: "13",
    Developer: "Ubisoft Milan",
  },
  {
    Name: "Kingdom Under Fire: Heroes",
    Platform: "XB",
    Year_of_Release: "2005",
    Genre: "Strategy",
    Publisher: "Deep Silver",
    NA_Sales: "0.11",
    EU_Sales: "0.03",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.15",
    Critic_Score: "78",
    Critic_Count: "55",
    User_Score: "7.5",
    User_Count: "23",
    Developer: "Phantagram",
  },
  {
    Name: "Armored Core: For Answer",
    Platform: "PS3",
    Year_of_Release: "2008",
    Genre: "Simulation",
    Publisher: "Ubisoft",
    NA_Sales: "0.06",
    EU_Sales: "0.02",
    JP_Sales: "0.1",
    Other_Sales: "0.01",
    Global_Sales: "0.19",
    Critic_Score: "62",
    Critic_Count: "22",
    User_Score: "7.6",
    User_Count: "31",
    Developer: "From Software",
  },
  {
    Name: "Shaun White Skateboarding",
    Platform: "PS3",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Ubisoft",
    NA_Sales: "0.11",
    EU_Sales: "0.05",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.19",
    Critic_Score: "61",
    Critic_Count: "26",
    User_Score: "6.5",
    User_Count: "8",
    Developer: "Ubisoft Montreal",
  },
  {
    Name: "Dark Arena",
    Platform: "GBA",
    Year_of_Release: "2002",
    Genre: "Shooter",
    Publisher: "THQ",
    NA_Sales: "0.03",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.04",
    Critic_Score: "65",
    Critic_Count: "17",
    Developer: "Graphic State",
  },
  {
    Name: "WCW/nWo Revenge",
    Platform: "N64",
    Year_of_Release: "1998",
    Genre: "Fighting",
    Publisher: "THQ",
    NA_Sales: "1.94",
    EU_Sales: "0.39",
    JP_Sales: "0.03",
    Other_Sales: "0.02",
    Global_Sales: "2.38",
  },
  {
    Name: "Disney Planes Fire & Rescue",
    Platform: "WiiU",
    Year_of_Release: "2014",
    Genre: "Action",
    Publisher: "Disney Interactive Studios",
    NA_Sales: "0.01",
    EU_Sales: "0.01",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Ultimate Fighting Championship",
    Platform: "PS",
    Year_of_Release: "2000",
    Genre: "Fighting",
    Publisher: "Ubisoft",
    NA_Sales: "0.14",
    EU_Sales: "0.09",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.25",
    Critic_Score: "53",
    Critic_Count: "6",
    User_Score: "7.4",
    User_Count: "16",
    Developer: "Opus",
  },
  {
    Name: "We Sing Encore",
    Platform: "Wii",
    Year_of_Release: "2010",
    Genre: "Misc",
    Publisher: "Nordic Games",
    NA_Sales: "0",
    EU_Sales: "0.39",
    JP_Sales: "0",
    Other_Sales: "0.06",
    Global_Sales: "0.45",
  },
  {
    Name: "L.A. Noire",
    Platform: "PS3",
    Year_of_Release: "2011",
    Genre: "Adventure",
    Publisher: "Take-Two Interactive",
    NA_Sales: "1.27",
    EU_Sales: "1.29",
    JP_Sales: "0.12",
    Other_Sales: "0.49",
    Global_Sales: "3.17",
    Critic_Score: "89",
    Critic_Count: "78",
    User_Score: "7.7",
    User_Count: "1010",
    Developer: "Team Bondi",
  },
  {
    Name: "Loving Life with Hello Kitty & Friends",
    Platform: "DS",
    Year_of_Release: "2011",
    Genre: "Misc",
    Publisher: "Rising Star Games",
    NA_Sales: "0.13",
    EU_Sales: "0.07",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.23",
  },
  {
    Name: "Dragon Quest Heroes: The World's Tree Woe and the Blight Below",
    Platform: "PS4",
    Year_of_Release: "2015",
    Genre: "Action",
    Publisher: "Square Enix",
    NA_Sales: "0.17",
    EU_Sales: "0.13",
    JP_Sales: "0.37",
    Other_Sales: "0.06",
    Global_Sales: "0.74",
  },
  {
    Name: "Meikyuu Cross Blood: Reloaded",
    Platform: "X360",
    Year_of_Release: "2011",
    Genre: "Action",
    Publisher: "Unknown",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.02",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "Puppet Show 3: Lost Town",
    Platform: "PC",
    Year_of_Release: "2011",
    Genre: "Puzzle",
    Publisher: "Focus Home Interactive",
    NA_Sales: "0",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.02",
  },
  {
    Name: "R-Type Command",
    Platform: "PSP",
    Year_of_Release: "2007",
    Genre: "Strategy",
    Publisher: "Rising Star Games",
    NA_Sales: "0.05",
    EU_Sales: "0",
    JP_Sales: "0.01",
    Other_Sales: "0.01",
    Global_Sales: "0.07",
    Critic_Score: "69",
    Critic_Count: "29",
    User_Score: "6.5",
    User_Count: "6",
    Developer: "Irem",
  },
  {
    Name: "Star Driver: Kagayaki no Takuto - Ginga Bishounen Densetsu",
    Platform: "PSP",
    Year_of_Release: "2011",
    Genre: "Adventure",
    Publisher: "Namco Bandai Games",
    NA_Sales: "0",
    EU_Sales: "0",
    JP_Sales: "0.05",
    Other_Sales: "0",
    Global_Sales: "0.05",
  },
  {
    Name: "Colony Wars",
    Platform: "PS",
    Year_of_Release: "1997",
    Genre: "Simulation",
    Publisher: "Psygnosis",
    NA_Sales: "0.24",
    EU_Sales: "0.16",
    JP_Sales: "0",
    Other_Sales: "0.03",
    Global_Sales: "0.42",
    Critic_Score: "91",
    Critic_Count: "12",
    User_Score: "7.8",
    User_Count: "12",
    Developer: "Psygnosis",
  },
  {
    Name: "Battle of Giants: Dragons",
    Platform: "DS",
    Year_of_Release: "2009",
    Genre: "Strategy",
    Publisher: "Ubisoft",
    NA_Sales: "0.3",
    EU_Sales: "0.25",
    JP_Sales: "0",
    Other_Sales: "0.06",
    Global_Sales: "0.62",
    User_Score: "6",
    User_Count: "4",
    Developer: "Ubisoft Quebec",
  },
  {
    Name: "NFL Fever 2003",
    Platform: "XB",
    Year_of_Release: "2002",
    Genre: "Sports",
    Publisher: "Microsoft Game Studios",
    NA_Sales: "0.46",
    EU_Sales: "0.13",
    JP_Sales: "0",
    Other_Sales: "0.02",
    Global_Sales: "0.61",
    Critic_Score: "72",
    Critic_Count: "25",
    User_Score: "8.6",
    User_Count: "12",
    Developer: "Microsoft Game Studios",
  },
  {
    Name: "Rayman",
    Platform: "PS",
    Year_of_Release: "1995",
    Genre: "Platform",
    Publisher: "Ubisoft",
    NA_Sales: "1.54",
    EU_Sales: "1.33",
    JP_Sales: "0",
    Other_Sales: "0.16",
    Global_Sales: "3.03",
  },
  {
    Name: "Little League World Series Baseball: Double Play",
    Platform: "DS",
    Year_of_Release: "2010",
    Genre: "Sports",
    Publisher: "Activision",
    NA_Sales: "0.07",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0.01",
    Global_Sales: "0.07",
    Developer: "Activision",
  },
  {
    Name: "GTR Evolution",
    Platform: "PC",
    Year_of_Release: "2008",
    Genre: "Racing",
    Publisher: "Atari",
    NA_Sales: "0",
    EU_Sales: "0.02",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.03",
    Critic_Score: "83",
    Critic_Count: "19",
    User_Score: "8.2",
    User_Count: "63",
    Developer: "SimBin",
  },
  {
    Name: "MTX Mototrax",
    Platform: "PSP",
    Year_of_Release: "2006",
    Genre: "Racing",
    Publisher: "Activision",
    NA_Sales: "0.04",
    EU_Sales: "0",
    JP_Sales: "0",
    Other_Sales: "0",
    Global_Sales: "0.05",
    Critic_Score: "67",
    Critic_Count: "8",
    Developer: "Left Field Productions",
  },
  {
    Name: "Sonic Heroes",
    Platform: "XB",
    Year_of_Release: "2003",
    Genre: "Platform",
    Publisher: "Sega",
    NA_Sales: "0.41",
    EU_Sales: "0.43",
    JP_Sales: "0.01",
    Other_Sales: "0.05",
    Global_Sales: "0.9",
    Critic_Score: "73",
    Critic_Count: "28",
    User_Score: "7.6",
    User_Count: "34",
    Developer: "Sonic Team",
  },
  {
    Name: "Madden NFL 10",
    Platform: "X360",
    Year_of_Release: "2009",
    Genre: "Sports",
    Publisher: "Electronic Arts",
    NA_Sales: "2.52",
    EU_Sales: "0.09",
    JP_Sales: "0",
    Other_Sales: "0.22",
    Global_Sales: "2.83",
    Critic_Score: "85",
    Critic_Count: "58",
    User_Score: "6.1",
    User_Count: "90",
    Developer: "EA Tiburon",
  },
];
